server:
  port: 8067
  servlet:
    context-path: /administration

spring:
  application:
    name: AssaAmockRestApi

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./assamockdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mock:
  auth:
    api-key: dev-api-key
    user-id: 00000000-0000-0000-0000-000000000001
    access-key: dev-access-key